### ISSUE TITLE
I can't implement the current version in Android Studio 3.4.1

### ISSUE THREAD

**Issue by ahuynh359** [DreaminginCodeZH/MaterialProgressBar#86] opened 2019-05-19 14:09 UTC
I can't implement the library with the current version which causes the error

 "ERROR: Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-19:19 to overrid".

But when I use the 1.4.1 version, it finally works

**Comment by zhanghai** [comment] 2019-05-19 16:46
Duplicate of #84.

**Closed as completed by zhanghai** 2019-05-19 16:46 UTC
Labels: duplicate, invalid
