### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by WilsonKifua** [DreaminginCodeZH/MaterialProgressBar#50] opened 2017-02-15 10:29 UTC
How to customize the progress bar color

**Comment by zhanghai** [comment] 2017-02-15 10:31
Duplicate of #15

**Closed as completed** 2017-02-15 10:32 UTC
Labels: duplicate, question

**Comment by rabw** [comment] 2017-03-28 22:19
android:tint does not work for me, I'm making a circular progress bar if it makes any difference.

**Comment by rabw** [comment] 2017-03-28 22:26
OK, app:mpb_indeterminateTint working for me.
