### ISSUE TITLE
Big indeterminate (circular) Progress Bar looks blurry

### ISSUE THREAD

**Issue by rpgdev** [DreaminginCodeZH/MaterialProgressBar#30] opened 2016-06-30 13:36 UTC
Not sure if this is an issue or expected behaviour of android resource management but the big indeterminate (circular) Progress Bar looks blurry on android 4.2.2 (768x1280, 320dpi).

It may not be very noticeable in screenshot but here it is: [http://i.imgur.com/LRP6jlO.png](http://i.imgur.com/LRP6jlO.png) it's definitely noticeable on runtime.

**Comment by zhanghai** [comment] 2016-07-04 12:40
Cannot reproduce.

Does this happend on AVDs, or real devices, or both? Is this bug specific to some Android version?

**Comment by rpgdev** [comment] 2016-07-04 13:00
It's a genymotion Nexus 4 AVD using the sample app.

**Comment by zhanghai** [comment] 2016-07-04 13:01
Does this happen on any real devices? or other Android versions?

**Comment by rpgdev** [comment] 2016-07-04 13:05
I don't see it on other AVDs maybe because resolution is bigger. I'll try on a real device later today and report back.

**Comment by rpgdev** [comment] 2016-07-04 22:10
Issue is present on a real device too. Samsung galaxy s4 mini GT-9195. Screenshot: [http://i.imgur.com/xWq88kF.png](http://i.imgur.com/xWq88kF.png) 

Seems like a resource type is missing or something.

**Comment by zhanghai** [comment] 2016-07-05 08:34
That's really strange, you know this library draws with canvas commands instead of bitmaps. And you can see in the picture the edge of the horizontal progress bar is clear which is also drawn on canvas. I have no idea why this happens and I cannot reproduce it on my AVDs and real device.

**Comment by rpgdev** [comment] 2016-07-05 11:11
Yes, the others look fine except the big indeterminate circular progress bar. Even in the screenshot it looks like the wrong resource it's being displayed there.

**Comment by zhanghai** [comment] 2016-07-13 08:45
Cannot reproduce, not going to make it into the upcoming release.

**Comment by rpgdev** [comment] 2016-07-13 11:26
Do you use genymotion? It's free you could use it to create the same AVD I use and see if it can be reproduced there. Even though I could also reproduce it on a real device it's weird that you can't.

**Comment by zhanghai** [comment] 2016-07-13 16:08
No I don't use genymotion; and the bug seems weird to me because it only happens under certain conditions and the library is drawing with canvas commands which should not be rasterized like that.

Do you have any thought on what could be the cause of this bug? Or what exactly is the condition for reproducing this bug?

**Comment by tomdega** [comment] 2016-07-13 16:28
I was able to pinpoint the problem and reproduce it using genymotion. Take a look at my commit.

**Comment by rpgdev** [comment] 2016-07-13 17:47
@DreaminginCodeZH I haven't done anything at all, it just shows up on the sample app. I haven't looked into what could be the cause however @tomdega's commit has fixed it :) I tested on the genymotion AVD and real device and the issue isn't present. You should consider merging it before the next release.

**Comment by zhanghai** [comment] 2016-07-14 04:34
Aha, thanks @tomdega, I've got to the issue.

https://developer.android.com/guide/topics/graphics/hardware-accel.html#scaling

> The hardware accelerated 2D rendering pipeline was built first to support unscaled drawing, with some drawing operations degrading quality significantly at higher scale values. These operations are implemented as textures drawn at scale 1.0, transformed by the GPU. In API level <17, using these operations will result in scaling artifacts increasing with scale.

In our case `Canvas.drawArc` falls into the "Simple shape" category and got fixed on API 17. I'm looking into a proper fix (whether to use `View.setLayerType()` or try a fix similar to http://stackoverflow.com/a/16110530/2420519).

**Comment by zhanghai** [comment] 2016-07-14 04:44
Scaling manually requires much logic change and is difficult to maintain, and since this is only a backport, I'm going the `View.setLayerType()` way. Now trying to figure out where to add it.

**Comment by zhanghai** [comment] 2016-07-14 06:23
@rpgdev 

Could you please test the current sample app on API 16 (4.1), 17 (4.2), 18 (4.3) and 19 (4.4) and report on which platforms the circular progress bar draws properly?

The docs says scaling for `Canvas.drawArc()` is ok on API 17 but according to your issue content this is not the case (you are running 4.2.2 which is 17). This can be resulted from the library's calling `setStrokeJoin()` (because the native vector drawable does so). But the native vector drawable works reliably on API 20 (5.0), this should have been fixed somewhere between 17 and 20, undocumented. So if we can figure out that API level we can do a conditional fallback to software rendering without performance loss on higher API levels.

(Some legacy Android images are broken for kvm on linux so I'm unable to test these by myself, sorry.)

**Comment by tomdega** [comment] 2016-07-14 06:57
I'll make the test, will update soon.

UPDATE:
16:
![16](https://cloud.githubusercontent.com/assets/10662127/16830948/cb5f805a-49aa-11e6-9b3a-8bf17b245bba.png)

17:
![17](https://cloud.githubusercontent.com/assets/10662127/16830956/d2908c8e-49aa-11e6-820d-295134e10168.png)

18:
![18](https://cloud.githubusercontent.com/assets/10662127/16830960/d5897dc4-49aa-11e6-8234-cbe1c3de984e.png)

19:
![19](https://cloud.githubusercontent.com/assets/10662127/16830967/de1fa648-49aa-11e6-9128-75d926dca47c.png)

so api <= 17 I guess.

**Comment by zhanghai** [comment] 2016-07-14 07:26
@tomdega @rpgdev Thank you very much!

**Closed as completed** 2016-07-14 07:25 UTC
Labels: bug, help wanted

**Comment by rpgdev** [comment] 2016-07-14 11:00
Thank you so much guys!
